version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: webshop
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    volumes:
      - pgdata:/var/lib/postgresql/data
    stdin_open: true
    tty: true
    networks:
      - postgres

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  data:
  node_modules:
  pgdata: